### ISSUE TITLE
resin-rtl-sdr base docker image Dockerfile

### ISSUE THREAD

**Issue by johnboiles** [mdp/AtlantaWaterMeter#1]
Looks like a really neat project. Looking forward to seeing if I can adapt this to my smartmeters when I get home.

Is the Dockerfile for mpercival/resin-rtl-sdr available somewhere? Would be super interested to know what's in that Docker image.

**Comment by mdp** [comment]
Sorry, should have linked to it in the docs. The dockerfile for it is located in https://github.com/mdp/AtlantaWaterMeter/tree/master/Baseimage
