### ISSUE TITLE
R900M Cubic Meters vs CCF

### ISSUE THREAD

**Issue by pansegrau** [mdp/AtlantaWaterMeter#2]
My Neptune R900M meter uses Cubic Meters for consumption (metric in Canada).  Therefore I lowered the divisor on line 22 of Daemon.sh from 10000 to 1000 and changed the text description on line 23 from "CCF" to "Cubic Meters".  The consumption now reads the same as on the actual meter's display.

**Comment by mdp** [comment]
I'll try and get an update out for this, should be pretty easy. Thanks!

**Comment by pansegrau** [comment]
I borrowed your code and altered it to monitor two R900M meters (a main meter and agricultural meter).  The new program also calculates the difference in consumption between the two meters for residential billing.  The consumption is displayed in Cubic Meters.
I am not a coder but with enough attempts I can get it to do what I want it to do.  
https://github.com/pansegrau/Lake-Country-R900M-Water-Meter-X2
