### ISSUE TITLE
How to find api key STATX

### ISSUE THREAD

**Issue by pansegrau** [mdp/AtlantaWaterMeter#3]
I would like to send the consumption data to Statx on my phone.

Where can I find statx details for the following variables?

STATX_APIKEY
STATX_AUTHTOKEN
STATX_GROUPID
STATX_STATID

Thanks

**Comment by mdp** [comment]
I wish it was easier, but you can only get this from their API. I have a CLI that will do most of it - https://github.com/mdp/go-statx
