### ISSUE TITLE
Error connecting to spectrum server

### ISSUE THREAD

**Issue by DavyNixon** [mdp/AtlantaWaterMeter#4]
I've managed to get this up and running, but now receiving the following error:

Error connecting to spectrum server: dial tcp 127.0.0.1:1234: getsockopt: connection refused

Any ideas how to fix this? Thanks for your help.

**Comment by andrewlively** [comment]
@DavyNixon Don't know if you still were working on this or not, but make sure you are also running a `rtl_tcp` instance. Once I had that then it worked just fine.

**Comment by mdp** [comment]
@DavyNixon did you ever get this working? Feel free to re-open if not.
